// The spools SDK. Entry layer (wind/entries/events) lands in T-012
// (docs/SDK-API.md is the map).
export { newSpool, openSpool, Spool, DEFAULT_RELAY, deriveSignaling, NotImplementedError } from './spool'
export type { NewSpoolOptions, OpenSpoolOptions } from './spool'
export { Entry } from './entry'
export type { EntryChange, WindInput } from './entry'
export { parseSpoolLink, buildSpoolLink, generateCode, isValidCode, SpoolLinkError } from './link'
export type { ParsedLink, BuildLinkInput } from './link'
export { SpoolEngine } from './engine'
export type { SpoolEngineOptions, SpoolStatus } from './engine'
export { SpoolHistoryError } from './history'
export type { EntrySnapshot } from './history'
export { SpoolKeyError, keyFingerprint } from './crypto'
export { EncryptedIndexeddbPersistence } from './encrypted-idb'
export { createEncryptedWebSocketClass, TRANSPORT_MAGIC } from './encrypted-ws'
