// The spools SDK. Entry layer (wind/entries/events) lands in T-012
// (docs/SDK-API.md is the map).
export { newSpool, openSpool, importSpool, Spool, DEFAULT_RELAY, deriveSignaling } from './spool'
export type { NewSpoolOptions, OpenSpoolOptions, ImportSpoolOptions } from './spool'
export { SpoolExportError, EXPORT_FORMAT, EXPORT_VERSION } from './export'
export type { SpoolExport } from './export'
export { stash } from './stash'
export type { StashedSpool } from './stash'
export { Entry } from './entry'
export type { EntryChange, WindInput } from './entry'
export { parseSpoolLink, buildSpoolLink, generateCode, isValidCode, SpoolLinkError } from './link'
export type { ParsedLink, BuildLinkInput } from './link'
export { SpoolEngine, ROOM_FULL_CLOSE_CODE } from './engine'
export type { SpoolEngineOptions, SpoolStatus } from './engine'
export type { Awareness } from 'y-protocols/awareness'
export { SpoolHistoryError } from './history'
export type { EntrySnapshot } from './history'
export { SpoolKeyError, keyFingerprint } from './crypto'
export { EncryptedIndexeddbPersistence } from './encrypted-idb'
export { createEncryptedWebSocketClass, TRANSPORT_MAGIC } from './encrypted-ws'
export { DEPOSIT_MAGIC, POCKET_VERSION } from './pocket'
export type { PocketState, PocketPhase } from './pocket'
